"""
Extract donatable item IDs from Grimshire's Unity Addressable bundles.
Scans all .bundle files in the game's StreamingAssets directory, reads
InventoryItem ScriptableObjects, and classifies them by donation flag.

ItemFlags (from decompiled Assembly-CSharp/ItemFlags.cs):
  donatePlant   = 32768
  donateMineral = 65536
  donateFish    = 524288

Run from the project root:
  python server/helpers/extractMuseumItems.py

Requires: pip install unitypy
Output:   server/helpers/museum_items.json
"""

import os
import json
import UnityPy

BUNDLES_DIR = r"C:\Program Files (x86)\Steam\steamapps\common\Grimshire\Grimshire_Data\StreamingAssets\aa\StandaloneWindows64"
OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "museum_items.json")
GAME_ID_MAPS_PATH = os.path.join(os.path.dirname(__file__), "game_id_maps.json")

FLAG_DONATE_PLANT   = 32768
FLAG_DONATE_MINERAL = 65536
FLAG_DONATE_FISH    = 524288

# Items confirmed as non-donatable despite appearing in FishCatchMsgTable.
# fish_ids comes from catch messages (includes junk like Stick), not from donateFish flag.
NON_DONATABLE_IDS = {
    581,  # Sickly Fish — debuff catch, not a museum specimen
    674,  # Stick — junk catch, not a museum specimen
    827,  # Bottled Surprise — treasure catch, not a museum specimen
}

donate_fish    = set()
donate_mineral = set()
donate_plant   = set()
items_found    = 0

print(f"Scanning bundles in: {BUNDLES_DIR}")

bundle_files = [f for f in os.listdir(BUNDLES_DIR) if f.endswith(".bundle")]
print(f"Found {len(bundle_files)} .bundle files")

for bundle_name in bundle_files:
    bundle_path = os.path.join(BUNDLES_DIR, bundle_name)
    try:
        env = UnityPy.load(bundle_path)
    except Exception as e:
        print(f"  Skipping {bundle_name}: {e}")
        continue

    for obj in env.objects:
        if obj.type.name != "MonoBehaviour":
            continue
        try:
            tree = obj.read_typetree()
        except Exception:
            continue

        # InventoryItem ScriptableObjects have an 'm_ID' field (the game item ID)
        # and a 'flags' field containing the ItemFlags bitmask.
        item_id = tree.get("m_ID") or tree.get("ID")
        flags   = tree.get("flags")

        if item_id is None or flags is None:
            continue
        if not isinstance(item_id, int) or not isinstance(flags, int):
            continue
        if item_id <= 0:
            continue

        items_found += 1
        if flags & FLAG_DONATE_FISH:
            donate_fish.add(item_id)
        if flags & FLAG_DONATE_MINERAL:
            donate_mineral.add(item_id)
        if flags & FLAG_DONATE_PLANT:
            donate_plant.add(item_id)

print(f"\nInventoryItem-like objects found: {items_found}")
print(f"  donateFish:    {len(donate_fish)}")
print(f"  donateMineral: {len(donate_mineral)}")
print(f"  donatePlant:   {len(donate_plant)}")

# If extraction found nothing for fish, fall back to fish_ids from game_id_maps.json
# (those are sourced from FishCatchMsgTable and are known-good).
if not donate_fish:
    print("\nNo donateFish items found via bundle scan — falling back to fish_ids from game_id_maps.json")
    with open(GAME_ID_MAPS_PATH, encoding="utf-8") as f:
        maps = json.load(f)
    donate_fish = set(maps.get("fish_ids", [])) - NON_DONATABLE_IDS
    print(f"  Loaded {len(donate_fish)} fish IDs from game_id_maps.json (after exclusions)")
else:
    donate_fish -= NON_DONATABLE_IDS

result = {
    "_note": "Generated by extractMuseumItems.py. donateFish/donateMineral/donatePlant IDs match ItemFlags in Assembly-CSharp/ItemFlags.cs.",
    "donateFish":    sorted(donate_fish),
    "donateMineral": sorted(donate_mineral),
    "donatePlant":   sorted(donate_plant),
}

with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump(result, f, indent=2)

print(f"\nWritten to {OUTPUT_PATH}")
